### ISSUE TITLE
Workload fails to deploy in sandbox after running testing-scanning-supplychain recipe

### ISSUE THREAD

**Issue by carpeliam** [Tanzu-Solutions-Engineering/tap-sandbox-cookbooks#1]
We're looking to reconfigure the TAP VIP Sandbox to use a testing/scanning supply chain instead of the default basic supply chain.

**Steps to reproduce:**

1. create new sandbox instance at https://tanzu.academy/guides/developer-sandbox-vip
2. create/run `.kube/set-context.sh` on local machine to access Developer Sandbox from local machine
3. follow steps within [recipe](https://github.com/Tanzu-Solutions-Engineering/tap-sandbox-cookbooks/blob/main/testing-scanning/README.md) to apply overlay
    1. We tried running this both within a cloned copy of the `tap-sandbox-cookbooks` repo and without a local cloned copy
    2. the modified secret had some of the following properties:
        ```yaml
        supply_chain: testing_scanning
        metadata_store:
          ns_for_export_app_cert: '*'
        namespace_provisioner:
          controller: false
          gitops_install:
            ref: origin/main
            subPath: testing-scanning/namespace-provisioner/namespaces
            url: https://github.com/Tanzu-Solutions-Engineering/tap-sandbox-cookbooks
        ootb_supply_chain_testing_scanning:
          registry:
            server: us-east1-docker.pkg.dev
            repository: tap-sandbox-dev/tapv-sweet-pig
          gitops:
            ssh_secret: ""
        ```
4. Deploy a workload via `tanzu workload apply ...`

**Expected behavior:**
Deployed workload goes through testing/scanning supply chain

**Actual behavior:**
Workload fails to deploy, and running `tanzu apps workload get tap-sensors-sensor` returns the following message:
> Workload [TemplateRejectedByAPIServer]:   unable to apply object [apps/tap-sensors-sensor] for resource [source-provider] in supply chain [source-test-scan-to-url]: failed to get unstructured [apps/tap-sensors-sensor] from api server: gitrepositories.source.toolkit.fluxcd.io "tap-sensors-sensor" is forbidden: User "system:serviceaccount:apps:default" cannot get resource "gitrepositories" in API group "source.toolkit.fluxcd.io" in the namespace "apps"
